wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 12
EPOCHS:
  desc: null
  value: 35
HEIGHT:
  desc: null
  value: 128
LEARNING_RATE:
  desc: null
  value: 0.0001
SEED:
  desc: null
  value: 2023
VIDEO_LENGTH:
  desc: null
  value: 50
WIDTH:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1678354532.715328
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 16
      - 23
      4: 3.9.12
      5: 0.13.11
      8:
      - 5
